// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Van from "./Van.res.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as VanjsCore from "vanjs-core";

var element = document.getElementById("root");

var root = (element == null) ? Js_exn.raiseError("Root element not found") : element;

VanjsCore.default.add(root, Van.Tags.createTag(undefined, "span"));

export {
  root ,
}
/* element Not a pure module */
