// Generated by ReScript, PLEASE EDIT WITH CARE

import * as VanjsCore from "vanjs-core";

function resolveNamespace(ns) {
  if (typeof ns === "object") {
    return ns._0;
  }
  switch (ns) {
    case "Html" :
        return ;
    case "Svg" :
        return "http://www.w3.org/2000/svg";
    case "MathMl" :
        return "http://www.w3.org/1998/Math/MathML";
    
  }
}

function createTag(nsOpt, tagName) {
  var ns = nsOpt !== undefined ? nsOpt : "Html";
  var n = resolveNamespace(ns);
  var proxy = n !== undefined ? VanjsCore.default.tags(n) : VanjsCore.default.tags();
  console.log(proxy(tagName));
  return (function(tagsProxy, tagName) {
        return tagsProxy[tagName]
      })(proxy, tagName)();
}

var Tags = {
  resolveNamespace: resolveNamespace,
  createTag: createTag
};

export {
  Tags ,
}
/* vanjs-core Not a pure module */
